# Generated by Django 5.2 on 2025-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='company_picture/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('telegram', models.CharField(blank=True, max_length=55, null=True)),
                ('instagram', models.CharField(blank=True, max_length=55, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=55, null=True)),
                ('about_us', models.TextField()),
            ],
        ),
    ]
